# Form implementation generated from reading ui file 'C:\Users\admin\PycharmProjects\TuduylaptrinhGit\MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 343)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\admin\\PycharmProjects\\TuduylaptrinhGit\\../LearnPrimeNumber/images/3099385_woman_student_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 10, 351, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(170, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEditN = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditN.setGeometry(QtCore.QRect(80, 80, 321, 31))
        self.lineEditN.setObjectName("lineEditN")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 250, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lineEditPrime = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditPrime.setGeometry(QtCore.QRect(80, 160, 321, 31))
        self.lineEditPrime.setObjectName("lineEditPrime")
        self.lineEditEven = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditEven.setGeometry(QtCore.QRect(80, 200, 321, 31))
        self.lineEditEven.setObjectName("lineEditEven")
        self.lineEditOdd = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEditOdd.setGeometry(QtCore.QRect(80, 250, 321, 31))
        self.lineEditOdd.setObjectName("lineEditOdd")
        self.pushButtonOK = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonOK.setGeometry(QtCore.QRect(190, 120, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.pushButtonOK.setFont(font)
        self.pushButtonOK.setObjectName("pushButtonOK")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Baitapnhom"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">List Of Number</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Nhập n:"))
        self.label_3.setText(_translate("MainWindow", "Prime:"))
        self.label_4.setText(_translate("MainWindow", "Even:"))
        self.label_5.setText(_translate("MainWindow", "Odd:"))
        self.pushButtonOK.setText(_translate("MainWindow", "OK"))
